name: panel
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pandas
  - panel
  - holoviews
  - hvplot
  - jupyterlab
  - pytest
  - appmode
  - pip
# pip
  - pip:
      - mortgage
# install @pyviz/jupyterlab_pyviz jupyter labextension afterwards as well if using jupyterlab
